### PR TITLE
Total rewrite

### PR DESCRIPTION
**Pull request by Misko-2083**
- Many changes
- Merged all the dialogs in two form dialogs and merged them into one notebook dialog
* Translation will have to be redone (sorry Jerry :rofl:)

### CODE REVIEW

**Comment by jerry3904** [comment]
I will definitely take a look, thanks.

I just added a new feature to the current mx-idesktool called "Write:
directly edit an icon file" Very handy--*take a look*. It would not be hard
to merge with your new creation.

BTW: any coronavirus over there?

Jerry

**Comment by Misko-2083** [comment]
The write feature already exists in the second tab.
I named it Open Config File. https://imgur.com/h29pRZH.png

**Comment by jerry3904** [comment]
Not the config file, the *.lnk file

**Comment by jerry3904** [comment]
https://imgur.com/4IxFwfu.png

**Comment by Misko-2083** [comment]
I see, I will add it.

**Pull request closed without merging**
